name: Updater (WIP)

on:
  # Run every Sunday at midnight (UTC)
  schedule:
    - cron: '0 0 * * 0'
  # Allows manual execution from GitHub Actions tab
  workflow_dispatch:

# Provide permission to update the repository
permissions:
  contents: write

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4  # ✅ Updated to latest version

      - name: Run HugoBlox Updater
        uses: HugoBlox/gh-action-updater@v1
        with:
          feed-url: https://hugoblox.com/rss.xml
          readme-section: news
          branch: main

